.PHONY: clean All

All:
	@echo "----------Building project:[ vjr - Release ]----------"
	@$(MAKE) -f  "vjr.mk"
clean:
	@echo "----------Cleaning project:[ vjr - Release ]----------"
	@$(MAKE) -f  "vjr.mk" clean
