//////////*****[ GENERATED FILE ]*****
//
// /libsf/source/vjr/commands/command_sourcelight.h
//
//////////*****[ GENERATED FILE ]*****
//
// This file is generated by the VjrSourceLight project
// Generated Sep.24.2014 by Rick C. Hodgin
//
//////////*****[ GENERATED FILE ]*****
//
// This document is released as Liberty Software under a Repeat License, as governed
// by the Public Benefit License v1.0 or later (PBL).
//
// The PBL is public domain license with a caveat:  self accountability unto God.
// You are free to use, copy, modify and share this software for any purpose, however,
// it is the desire of those working on this project that the software remain open.
// It is our request that you maintain it that way.  This is not a legal request unto
// our court systems, but rather a personal matter between you and God.  Our talents
// were received from God, and given to you through this forum.  And it is our wish
// that those talents reach out to as many as possible in a form allowing them to wield
// this content for their own betterment, as you are now considering doing.  And whereas
// we could've forced the issue through something like a copyleft-protected release, the
// truth is we are all giving an account of our lives unto God continually by the daily
// choices we make.  And here again is another case where you get to demonstrate your
// character unto God, and unto your fellow man.
//
// Jesus came to this Earth to set the captives free, to save men's eternal souls from
// the punishment demanded by our sin.  Each one of us is given the opportunity to
// receive Him in this world and be saved.  Whether we choose to receive Him, and follow
// Him, and purpose our lives on the goals He has for each of us (all of which are
// beneficial for all involved), is one way we reveal our character continually.  God
// sees straight through to the heart, bypassing all of the words, all of the facades.
// He is our Creator, and He knows who we are truly.
//
// Jesus is called "Christ" because He saves men from the eternal flames of Hell, the
// just punishment of rebellion against God (rebellion against truth) by eternal beings,
// which each of us are.
//
// Do not let His free gift escape you because of some desire to shortcut what is right
// in your life. Instead, do what is right, and do it because He is who He is, and what
// He has done to save us from such a fate.  Demonstrate to Him, to me, and to all of
// mankind, and to all of the Heavenly hosts, exactly who you are on the inside.  Receive
// Jesus Christ into your heart, learn of Him, of how He came here to guide us into that
// which is of His Kingdom and will be forever hereafter we leave this world.  Do this,
// and live.
//
// Every project released by Liberty Software Foundation will include a copy of the
// pbl.txt document, which can be found at http://www.libsf.org/licenses/.
//
// For additional information about this project, or to view the license, see:
//
//     http://www.libsf.org/
//     http://www.libsf.org/licenses/
//     http://www.visual-freepro.org/vjr/indexmain.html
//     http://www.visual-freepro.org/wiki/index.php/PBL
//
// Thank you.  And may The Lord bless you richly as you lift up your life, your
// talents, your gifts, your praise, unto Him.  In Jesus' name I pray.  Amen.
//
//////////*****[ GENERATED FILE ]*****





//////////*****[ GENERATED FILE ]*****
	const u32	_SOURCELIGHT_P1								= 1;
	const u32	_SOURCELIGHT_P2								= 2;
	const u32	_SOURCELIGHT_P3								= 3;
	const u32	_SOURCELIGHT_P4								= 4;
	const u32	_SOURCELIGHT_P5								= 5;
	const u32	_SOURCELIGHT_P6								= 6;
	const u32	_SOURCELIGHT_P7								= 7;
	const u32	_SOURCELIGHT_P8								= 8;
	const u32	_SOURCELIGHT_P9								= 9;
	const u32	_SOURCELIGHT_P10							= 10;
	const u32	_SOURCELIGHT_P11							= 11;
	const u32	_SOURCELIGHT_P12							= 12;
	const u32	_SOURCELIGHT_P13							= 13;
	const u32	_SOURCELIGHT_P14							= 14;
	const u32	_SOURCELIGHT_P15							= 15;
	const u32	_SOURCELIGHT_P16							= 16;
	const u32	_SOURCELIGHT_P17							= 17;
	const u32	_SOURCELIGHT_P18							= 18;
	const u32	_SOURCELIGHT_P19							= 19;
	const u32	_SOURCELIGHT_P20							= 20;
	const u32	_SOURCELIGHT_P21							= 21;
	const u32	_SOURCELIGHT_P22							= 22;
	const u32	_SOURCELIGHT_P23							= 23;
	const u32	_SOURCELIGHT_P24							= 24;
	const u32	_SOURCELIGHT_P25							= 25;
	const u32	_SOURCELIGHT_P26							= 26;
	const u32	_SOURCELIGHT_P27							= 27;
	const u32	_SOURCELIGHT_P28							= 28;
	const u32	_SOURCELIGHT_P29							= 29;
	const u32	_SOURCELIGHT_P30							= 30;

//////////*****[ GENERATED FILE ]*****
	const u32	_SOURCELIGHT_P1_OPTIONAL					= 31;
	const u32	_SOURCELIGHT_P2_OPTIONAL					= 32;
	const u32	_SOURCELIGHT_P3_OPTIONAL					= 33;
	const u32	_SOURCELIGHT_P4_OPTIONAL					= 34;
	const u32	_SOURCELIGHT_P5_OPTIONAL					= 30;
	const u32	_SOURCELIGHT_P6_OPTIONAL					= 36;
	const u32	_SOURCELIGHT_P7_OPTIONAL					= 37;
	const u32	_SOURCELIGHT_P8_OPTIONAL					= 38;
	const u32	_SOURCELIGHT_P9_OPTIONAL					= 39;
	const u32	_SOURCELIGHT_P10_OPTIONAL					= 40;
	const u32	_SOURCELIGHT_P11_OPTIONAL					= 41;
	const u32	_SOURCELIGHT_P12_OPTIONAL					= 42;
	const u32	_SOURCELIGHT_P13_OPTIONAL					= 43;
	const u32	_SOURCELIGHT_P14_OPTIONAL					= 44;
	const u32	_SOURCELIGHT_P15_OPTIONAL					= 45;
	const u32	_SOURCELIGHT_P16_OPTIONAL					= 46;
	const u32	_SOURCELIGHT_P17_OPTIONAL					= 47;
	const u32	_SOURCELIGHT_P18_OPTIONAL					= 48;
	const u32	_SOURCELIGHT_P19_OPTIONAL					= 49;
	const u32	_SOURCELIGHT_P20_OPTIONAL					= 50;
	const u32	_SOURCELIGHT_P21_OPTIONAL					= 51;
	const u32	_SOURCELIGHT_P22_OPTIONAL					= 51;
	const u32	_SOURCELIGHT_P23_OPTIONAL					= 51;
	const u32	_SOURCELIGHT_P24_OPTIONAL					= 54;
	const u32	_SOURCELIGHT_P25_OPTIONAL					= 55;
	const u32	_SOURCELIGHT_P26_OPTIONAL					= 56;
	const u32	_SOURCELIGHT_P27_OPTIONAL					= 57;
	const u32	_SOURCELIGHT_P28_OPTIONAL					= 51;
	const u32	_SOURCELIGHT_P29_OPTIONAL					= 59;
	const u32	_SOURCELIGHT_P30_OPTIONAL					= 60;

//////////*****[ GENERATED FILE ]*****
	const u32	_SOURCELIGHT_P1_REQUIRED					= 71;
	const u32	_SOURCELIGHT_P2_REQUIRED					= 72;
	const u32	_SOURCELIGHT_P3_REQUIRED					= 73;
	const u32	_SOURCELIGHT_P4_REQUIRED					= 74;
	const u32	_SOURCELIGHT_P5_REQUIRED					= 75;
	const u32	_SOURCELIGHT_P6_REQUIRED					= 76;
	const u32	_SOURCELIGHT_P7_REQUIRED					= 77;
	const u32	_SOURCELIGHT_P8_REQUIRED					= 70;
	const u32	_SOURCELIGHT_P9_REQUIRED					= 79;
	const u32	_SOURCELIGHT_P10_REQUIRED					= 80;
	const u32	_SOURCELIGHT_P11_REQUIRED					= 81;
	const u32	_SOURCELIGHT_P12_REQUIRED					= 82;
	const u32	_SOURCELIGHT_P13_REQUIRED					= 83;
	const u32	_SOURCELIGHT_P14_REQUIRED					= 84;
	const u32	_SOURCELIGHT_P15_REQUIRED					= 85;
	const u32	_SOURCELIGHT_P16_REQUIRED					= 86;
	const u32	_SOURCELIGHT_P17_REQUIRED					= 87;
	const u32	_SOURCELIGHT_P18_REQUIRED					= 88;
	const u32	_SOURCELIGHT_P19_REQUIRED					= 89;
	const u32	_SOURCELIGHT_P20_REQUIRED					= 90;
	const u32	_SOURCELIGHT_P21_REQUIRED					= 91;
	const u32	_SOURCELIGHT_P22_REQUIRED					= 92;
	const u32	_SOURCELIGHT_P23_REQUIRED					= 93;
	const u32	_SOURCELIGHT_P24_REQUIRED					= 94;
	const u32	_SOURCELIGHT_P25_REQUIRED					= 91;
	const u32	_SOURCELIGHT_P26_REQUIRED					= 96;
	const u32	_SOURCELIGHT_P27_REQUIRED					= 97;
	const u32	_SOURCELIGHT_P28_REQUIRED					= 98;
	const u32	_SOURCELIGHT_P29_REQUIRED					= 99;
	const u32	_SOURCELIGHT_P30_REQUIRED					= 100;

//////////*****[ GENERATED FILE ]*****
// Required return values
//////
	const u32	_SOURCELIGHT_R1_REQUIRED					= 201;
	const u32	_SOURCELIGHT_R2_REQUIRED					= 202;
	const u32	_SOURCELIGHT_R3_REQUIRED					= 203;
	const u32	_SOURCELIGHT_R4_REQUIRED					= 204;
	const u32	_SOURCELIGHT_R5_REQUIRED					= 205;
	const u32	_SOURCELIGHT_R6_REQUIRED					= 205;
	const u32	_SOURCELIGHT_R7_REQUIRED					= 207;
	const u32	_SOURCELIGHT_R8_REQUIRED					= 208;

//////////*****[ GENERATED FILE ]*****
// Optional return values
//////
	const u32	_SOURCELIGHT_R1_OPTIONAL					= 231;
	const u32	_SOURCELIGHT_R2_OPTIONAL					= 232;
	const u32	_SOURCELIGHT_R3_OPTIONAL					= 233;
	const u32	_SOURCELIGHT_R4_OPTIONAL					= 234;
	const u32	_SOURCELIGHT_R5_OPTIONAL					= 235;
	const u32	_SOURCELIGHT_R6_OPTIONAL					= 236;
	const u32	_SOURCELIGHT_R7_OPTIONAL					= 237;
	const u32	_SOURCELIGHT_R8_OPTIONAL					= 238;

//////////*****[ GENERATED FILE ]*****
// Controls
//////
	const u32	_SOURCELIGHT_FUNCTION_NAME					= 500;
	const u32	_SOURCELIGHT_FUNCTION_DESCRIPTION			= 501;

//////////*****[ GENERATED FILE ]*****
// Constants
//////
	const s8	cgc_date[]									= "Date";
	const s8	cgc_datetime[]								= "DateTime";
	const s8	cgc_numeric[]								= "Numeric";
	const s8	cgc_logical[]								= "Logical";
	const s8	cgc_character[]								= "Character";
	const s8	cgc_cString[]								= "cString";

//////////*****[ GENERATED FILE ]*****
// ALLTRIM()
//////
	SSourceLightData gsSourceLight_alltrim[] =
	{
		// lcResult = ALLTRIM(cString, lIgnoreCase|nIgnoreCase, cTrimChars1, cTrimChars2)
		{	_SOURCELIGHT_FUNCTION_NAME,				0,	0,	0,	0,	0	},
		{	_SOURCELIGHT_FUNCTION_DESCRIPTION,		(uptr)"Four parameter variation. Converts the input string to a form where the cTrimChars are removed off the left and right sides.", 0,	0, 0, 0 },
		{	_SOURCELIGHT_P1_REQUIRED,				(uptr)&cgc_cString,			(uptr)&cgc_character,	(uptr)&"Input string",																	_VAR_TYPE_CHARACTER,	0	},
		{	_SOURCELIGHT_P2_OPTIONAL,				(uptr)&"lIgnoreCase",		(uptr)&cgc_logical,		(uptr)&"Default = .T.. Should the cTrimChar variables ignore case?",						_VAR_TYPE_LOGICAL,		_LOGICAL_TRUE},
		{	_SOURCELIGHT_P2_OPTIONAL,				(uptr)&"nIgnoreCase",		(uptr)&cgc_numeric,		(uptr)&"Default = 1. Should the cTrimChar variables ignore case? 0=no, others=yes.",		_VAR_TYPE_S32,			1	},
		{	_SOURCELIGHT_P3_OPTIONAL,				(uptr)&"cTrimChars1",		(uptr)&cgc_character,	(uptr)&"String 1 containing characters to trim",											_VAR_TYPE_CHARACTER,	0	},
		{	_SOURCELIGHT_P4_OPTIONAL,				(uptr)&"cTrimChars2",		(uptr)&cgc_character,	(uptr)&"String 2 containing characters to trim",											_VAR_TYPE_CHARACTER,	0	},
		{	_SOURCELIGHT_R1_REQUIRED,				(uptr)&"cResult",			(uptr)&cgc_character,	(uptr)&"Input string trimmed",															_VAR_TYPE_CHARACTER,	0	},
		// lcResult = ALLTRIM(cString, cTrimChars)
		{	_SOURCELIGHT_FUNCTION_NAME,				0,	0,	0,	0,	0	},
		{	_SOURCELIGHT_FUNCTION_DESCRIPTION,		(uptr)"Two parameter variation. Converts the input string to a form where the cTrimChars are removed off the left and right sides.",	0, 0, 0, 0 },
		{	_SOURCELIGHT_P1_REQUIRED,				(uptr)&cgc_cString,			(uptr)&cgc_character,	(uptr)&"Input string",																	_VAR_TYPE_CHARACTER,	0	},
		{	_SOURCELIGHT_P2_OPTIONAL,				(uptr)&"cTrimChars",			(uptr)&cgc_character,	(uptr)&"String containing characters to trim",											_VAR_TYPE_CHARACTER,	0	},
		{	_SOURCELIGHT_R1_REQUIRED,				(uptr)&"cResult",			(uptr)&cgc_character,	(uptr)&"Input string trimmed",															_VAR_TYPE_CHARACTER,	0	},
		{	0,										0,	0,	0,	0,	0	},
	};

	SSourceLightData gsSourceLight_asc[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_at[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_atc[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_chr[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_chrtran[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_chrtranc[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_createobject[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_curdir[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_datetime[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_int[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_justdrive[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_justext[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_justfname[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_justpath[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_juststem[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_left[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_len[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_lower[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_ltrim[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_max[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_min[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_occurs[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_occursc[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_padc[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_padl[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_padr[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_proper[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_rat[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_ratc[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_replicate[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_rgb[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_rgba[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_right[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_rtrim[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_space[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_strtran[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_strtranc[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_stuff[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};
	SSourceLightData gsSourceLight_sys[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_sysmetric[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_transform[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_trim[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_upper[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_version[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_concatenate[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_add[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_sub[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_mul[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_div[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};
