//////////*****[ GENERATED FILE ]*****
//
// /libsf/source/vjr/commands/command_sourcelight.h
//
//////
//    _     _ _     _____ _____ 
//   | |   (_) |__ / ____|  ___|
//   | |   | | '_ \\___ \|  __|
//   | |___| | |_) |___) | |
//   |_____|_|_.__/_____/|_|
//
//   Liberty Software Foundation
// and the Village Freedom Project
//   __     _______     ____  
//   \ \   / /  ___| __|  _ \ 
//    \ \ / /| |_ | '__| |_) |
//     \ V / |  _|| |  |  __/ 
//      \_/  |_|  |_|  |_|
//
//////////*****[ GENERATED FILE ]*****
//
// This file is generated by the VjrSourceLight project
// Generated Sep.24.2014 by Rick C. Hodgin
//
//////////*****[ GENERATED FILE ]*****
//
// This document is released as Liberty Software under a Repeat License, as governed
// by the Public Benefit License v1.0 or later (PBL).
//
// The PBL is public domain license with a caveat:  self accountability unto God.
// You are free to use, copy, modify and share this software for any purpose, however,
// it is the desire of those working on this project that the software remain open.
// It is our request that you maintain it that way.  This is not a legal request unto
// our court systems, but rather a personal matter between you and God.  Our talents
// were received from God, and given to you through this forum.  And it is our wish
// that those talents reach out to as many as possible in a form allowing them to wield
// this content for their own betterment, as you are now considering doing.  And whereas
// we could've forced the issue through something like a copyleft-protected release, the
// truth is we are all giving an account of our lives unto God continually by the daily
// choices we make.  And here again is another case where you get to demonstrate your
// character unto God, and unto your fellow man.
//
// Jesus came to this Earth to set the captives free, to save men's eternal souls from
// the punishment demanded by our sin.  Each one of us is given the opportunity to
// receive Him in this world and be saved.  Whether we choose to receive Him, and follow
// Him, and purpose our lives on the goals He has for each of us (all of which are
// beneficial for all involved), is one way we reveal our character continually.  God
// sees straight through to the heart, bypassing all of the words, all of the facades.
// He is our Creator, and He knows who we are truly.
//
// Jesus is called "Christ" because He saves men from the eternal flames of Hell, the
// just punishment of rebellion against God (rebellion against truth) by eternal beings,
// which each of us are.
//
// Do not let His free gift escape you because of some desire to shortcut what is right
// in your life. Instead, do what is right, and do it because He is who He is, and what
// He has done to save us from such a fate.  Demonstrate to Him, to me, and to all of
// mankind, and to all of the Heavenly hosts, exactly who you are on the inside.  Receive
// Jesus Christ into your heart, learn of Him, of how He came here to guide us into that
// which is of His Kingdom and will be forever hereafter we leave this world.  Do this,
// and live.
//
// Every project released by Liberty Software Foundation will include a copy of the
// pbl.txt document, which can be found at http://www.libsf.org/licenses/.
//
// For additional information about this project, or to view the license, see:
//
//     http://www.libsf.org/
//     http://www.libsf.org/licenses/
//     http://www.visual-freepro.org/vjr/indexmain.html
//     http://www.visual-freepro.org/wiki/index.php/PBL
//
// Thank you.  And may The Lord bless you richly as you lift up your life, your
// talents, your gifts, your praise, unto Him.  In Jesus' name I pray.  Amen.
//
//////////*****[ GENERATED FILE ]*****





//////////*****[ GENERATED FILE ]*****
	const u32	_SOURCELIGHT_P1								= 1;
	const u32	_SOURCELIGHT_P2								= 2;
	const u32	_SOURCELIGHT_P3								= 3;
	const u32	_SOURCELIGHT_P4								= 4;
	const u32	_SOURCELIGHT_P5								= 5;
	const u32	_SOURCELIGHT_P6								= 6;
	const u32	_SOURCELIGHT_P7								= 7;
	const u32	_SOURCELIGHT_P8								= 8;
	const u32	_SOURCELIGHT_P9								= 9;
	const u32	_SOURCELIGHT_P10							= 10;
	const u32	_SOURCELIGHT_P11							= 11;
	const u32	_SOURCELIGHT_P12							= 12;
	const u32	_SOURCELIGHT_P13							= 13;
	const u32	_SOURCELIGHT_P14							= 14;
	const u32	_SOURCELIGHT_P15							= 15;
	const u32	_SOURCELIGHT_P16							= 16;
	const u32	_SOURCELIGHT_P17							= 17;
	const u32	_SOURCELIGHT_P18							= 18;
	const u32	_SOURCELIGHT_P19							= 19;
	const u32	_SOURCELIGHT_P20							= 20;
	const u32	_SOURCELIGHT_P21							= 21;
	const u32	_SOURCELIGHT_P22							= 22;
	const u32	_SOURCELIGHT_P23							= 23;
	const u32	_SOURCELIGHT_P24							= 24;
	const u32	_SOURCELIGHT_P25							= 25;
	const u32	_SOURCELIGHT_P26							= 26;
	const u32	_SOURCELIGHT_P27							= 27;
	const u32	_SOURCELIGHT_P28							= 28;
	const u32	_SOURCELIGHT_P29							= 29;
	const u32	_SOURCELIGHT_P30							= 30;

//////////*****[ GENERATED FILE ]*****
	const u32	_SOURCELIGHT_P1_OPTIONAL					= 101;
	const u32	_SOURCELIGHT_P2_OPTIONAL					= 102;
	const u32	_SOURCELIGHT_P3_OPTIONAL					= 103;
	const u32	_SOURCELIGHT_P4_OPTIONAL					= 104;
	const u32	_SOURCELIGHT_P5_OPTIONAL					= 105;
	const u32	_SOURCELIGHT_P6_OPTIONAL					= 106;
	const u32	_SOURCELIGHT_P7_OPTIONAL					= 107;
	const u32	_SOURCELIGHT_P8_OPTIONAL					= 108;
	const u32	_SOURCELIGHT_P9_OPTIONAL					= 109;
	const u32	_SOURCELIGHT_P10_OPTIONAL					= 110;
	const u32	_SOURCELIGHT_P11_OPTIONAL					= 111;
	const u32	_SOURCELIGHT_P12_OPTIONAL					= 112;
	const u32	_SOURCELIGHT_P13_OPTIONAL					= 113;
	const u32	_SOURCELIGHT_P14_OPTIONAL					= 114;
	const u32	_SOURCELIGHT_P15_OPTIONAL					= 115;
	const u32	_SOURCELIGHT_P16_OPTIONAL					= 116;
	const u32	_SOURCELIGHT_P17_OPTIONAL					= 117;
	const u32	_SOURCELIGHT_P18_OPTIONAL					= 118;
	const u32	_SOURCELIGHT_P19_OPTIONAL					= 119;
	const u32	_SOURCELIGHT_P20_OPTIONAL					= 120;
	const u32	_SOURCELIGHT_P21_OPTIONAL					= 121;
	const u32	_SOURCELIGHT_P22_OPTIONAL					= 122;
	const u32	_SOURCELIGHT_P23_OPTIONAL					= 123;
	const u32	_SOURCELIGHT_P24_OPTIONAL					= 124;
	const u32	_SOURCELIGHT_P25_OPTIONAL					= 125;
	const u32	_SOURCELIGHT_P26_OPTIONAL					= 126;
	const u32	_SOURCELIGHT_P27_OPTIONAL					= 127;
	const u32	_SOURCELIGHT_P28_OPTIONAL					= 128;
	const u32	_SOURCELIGHT_P29_OPTIONAL					= 129;
	const u32	_SOURCELIGHT_P30_OPTIONAL					= 130;

//////////*****[ GENERATED FILE ]*****
	const u32	_SOURCELIGHT_P1_REQUIRED					= 200;
	const u32	_SOURCELIGHT_P2_REQUIRED					= 201;
	const u32	_SOURCELIGHT_P3_REQUIRED					= 202;
	const u32	_SOURCELIGHT_P4_REQUIRED					= 203;
	const u32	_SOURCELIGHT_P5_REQUIRED					= 204;
	const u32	_SOURCELIGHT_P6_REQUIRED					= 205;
	const u32	_SOURCELIGHT_P7_REQUIRED					= 206;
	const u32	_SOURCELIGHT_P8_REQUIRED					= 207;
	const u32	_SOURCELIGHT_P9_REQUIRED					= 208;
	const u32	_SOURCELIGHT_P10_REQUIRED					= 209;
	const u32	_SOURCELIGHT_P11_REQUIRED					= 210;
	const u32	_SOURCELIGHT_P12_REQUIRED					= 211;
	const u32	_SOURCELIGHT_P13_REQUIRED					= 212;
	const u32	_SOURCELIGHT_P14_REQUIRED					= 213;
	const u32	_SOURCELIGHT_P15_REQUIRED					= 214;
	const u32	_SOURCELIGHT_P16_REQUIRED					= 215;
	const u32	_SOURCELIGHT_P17_REQUIRED					= 216;
	const u32	_SOURCELIGHT_P18_REQUIRED					= 217;
	const u32	_SOURCELIGHT_P19_REQUIRED					= 218;
	const u32	_SOURCELIGHT_P20_REQUIRED					= 219;
	const u32	_SOURCELIGHT_P21_REQUIRED					= 220;
	const u32	_SOURCELIGHT_P22_REQUIRED					= 221;
	const u32	_SOURCELIGHT_P23_REQUIRED					= 222;
	const u32	_SOURCELIGHT_P24_REQUIRED					= 223;
	const u32	_SOURCELIGHT_P25_REQUIRED					= 224;
	const u32	_SOURCELIGHT_P26_REQUIRED					= 225;
	const u32	_SOURCELIGHT_P27_REQUIRED					= 226;
	const u32	_SOURCELIGHT_P28_REQUIRED					= 227;
	const u32	_SOURCELIGHT_P29_REQUIRED					= 228;
	const u32	_SOURCELIGHT_P30_REQUIRED					= 229;

//////////*****[ GENERATED FILE ]*****
	const u32	_SOURCELIGHT_LOGICAL_FLAG					= 300;
	const u32	_SOURCELIGHT_LOGICAL_FLAG_AFTER_PN			= 301;
	const u32	_SOURCELIGHT_LOGICAL_FLAG_AFTER_NAMED		= 302;
	const u32	_SOURCELIGHT_PN_LOGICAL_FLAG				= 332;

//////////*****[ GENERATED FILE ]*****
// Required return values
//////
	const u32	_SOURCELIGHT_R1_REQUIRED					= 1001;
	const u32	_SOURCELIGHT_R2_REQUIRED					= 1002;
	const u32	_SOURCELIGHT_R3_REQUIRED					= 1003;
	const u32	_SOURCELIGHT_R4_REQUIRED					= 1004;
	const u32	_SOURCELIGHT_R5_REQUIRED					= 1005;
	const u32	_SOURCELIGHT_R6_REQUIRED					= 1005;
	const u32	_SOURCELIGHT_R7_REQUIRED					= 1007;
	const u32	_SOURCELIGHT_R8_REQUIRED					= 1008;

//////////*****[ GENERATED FILE ]*****
// Optional return values
//////
	const u32	_SOURCELIGHT_R1_OPTIONAL					= 1101;
	const u32	_SOURCELIGHT_R2_OPTIONAL					= 1102;
	const u32	_SOURCELIGHT_R3_OPTIONAL					= 1103;
	const u32	_SOURCELIGHT_R4_OPTIONAL					= 1104;
	const u32	_SOURCELIGHT_R5_OPTIONAL					= 1105;
	const u32	_SOURCELIGHT_R6_OPTIONAL					= 1106;
	const u32	_SOURCELIGHT_R7_OPTIONAL					= 1107;
	const u32	_SOURCELIGHT_R8_OPTIONAL					= 1108;

//////////*****[ GENERATED FILE ]*****
// Controls
//////
	const u32	_SOURCELIGHT_FUNCTION_NAME					= 5000;
	const u32	_SOURCELIGHT_FUNCTION_DESCRIPTION			= 5001;

//////////*****[ GENERATED FILE ]*****
// Constants
//////
	const s8	cgc_sl_date[]								= "Date";
	const s8	cgc_sl_datetime[]							= "DateTime";
	const s8	cgc_sl_numeric[]							= "Numeric";
	const s8	cgc_sl_logical[]							= "Logical";
	const s8	cgc_sl_character[]							= "Character";
	const s8	cgc_sl_cString[]							= "cString";

//////////*****[ GENERATED FILE ]*****
// ALLTRIM()
//////
	SSourceLightData gsSourceLight_alltrim[] =
	{
		// lcResult = ALLTRIM(cString, lIgnoreCase|nIgnoreCase, cTrimChars1, cTrimChars2)
		{	_SOURCELIGHT_FUNCTION_NAME,				0,	0,	0,	0,	0	},
		{	_SOURCELIGHT_FUNCTION_DESCRIPTION,		(uptr)"Four parameter variation. Converts the input string to a form where the cTrimChars are removed off the left and right sides.", 0, 0, 0, 0 },
		{	_SOURCELIGHT_P1_REQUIRED,				(uptr)&cgc_sl_cString,		(uptr)&cgc_sl_character,	(uptr)&"Input string",																	_VAR_TYPE_CHARACTER,	0	},
		{	_SOURCELIGHT_P2_OPTIONAL,				(uptr)&"lIgnoreCase",		(uptr)&cgc_sl_logical,		(uptr)&"Default = .T.. Should the cTrimChar variables ignore case?",					_VAR_TYPE_LOGICAL,		_LOGICAL_TRUE},
		{	_SOURCELIGHT_P2_OPTIONAL,				(uptr)&"nIgnoreCase",		(uptr)&cgc_sl_numeric,		(uptr)&"Default = 1. Should the cTrimChar variables ignore case? 0=no, others=yes.",	_VAR_TYPE_S32,			1	},
		{	_SOURCELIGHT_P3_OPTIONAL,				(uptr)&"cTrimChars1",		(uptr)&cgc_sl_character,	(uptr)&"String 1 containing characters to trim",										_VAR_TYPE_CHARACTER,	0	},
		{	_SOURCELIGHT_P4_OPTIONAL,				(uptr)&"cTrimChars2",		(uptr)&cgc_sl_character,	(uptr)&"String 2 containing characters to trim",										_VAR_TYPE_CHARACTER,	0	},
		{	_SOURCELIGHT_R1_REQUIRED,				(uptr)&"cResult",			(uptr)&cgc_sl_character,	(uptr)&"Input string trimmed",															_VAR_TYPE_CHARACTER,	0	},
		// lcResult = ALLTRIM(cString, cTrimChars)
		{	_SOURCELIGHT_FUNCTION_NAME,				0,	0,	0,	0,	0	},
		{	_SOURCELIGHT_FUNCTION_DESCRIPTION,		(uptr)"Two parameter variation. Converts the input string to a form where the cTrimChars are removed off the left and right sides.",	0, 0, 0, 0 },
		{	_SOURCELIGHT_P1_REQUIRED,				(uptr)&cgc_sl_cString,		(uptr)&cgc_sl_character,	(uptr)&"Input string",																_VAR_TYPE_CHARACTER,	0	},
		{	_SOURCELIGHT_P2_OPTIONAL,				(uptr)&"cTrimChars",		(uptr)&cgc_sl_character,	(uptr)&"String containing characters to trim",									_VAR_TYPE_CHARACTER,	0	},
		{	_SOURCELIGHT_R1_REQUIRED,				(uptr)&"cResult",			(uptr)&cgc_sl_character,	(uptr)&"Input string trimmed",														_VAR_TYPE_CHARACTER,	0	},
		{	0,										0,	0,	0,	0,	0	},
	};

	SSourceLightData gsSourceLight_abs[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_acos[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_alp[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_asc[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_asin[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_at[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_atan[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_atc[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_atn2[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_bgr[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_bgra[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_blu[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_ceiling[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_chr[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_chrtran[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_chrtranc[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_colorize[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_cos[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_createobject[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_curdir[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_datetime[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_dtor[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_empty[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_evl[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_exp[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_floor[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_forceext[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_forcefname[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_forcepath[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_forcestem[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_fv[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_grayscale[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_grn[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_int[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_justdrive[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_justext[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_justfname[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_justpath[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_juststem[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_left[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_len[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_log[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_log10[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};


	SSourceLightData gsSourceLight_lower[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_ltrim[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_malp[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_max[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_min[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_mod[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_ncset[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_occurs[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_occursc[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_padc[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_padl[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_padr[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};
	
	SSourceLightData gsSourceLight_payment[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};
	
	SSourceLightData gsSourceLight_pi[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_proper[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_pv[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_ranger[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_ranger2[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_rat[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_ratc[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_red[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_replicate[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_rgb[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_rgba[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_right[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_round[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_rtod[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_rtrim[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_set[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_sign[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_sin[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_space[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_sqrt[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_strtran[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_strtranc[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_stuff[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};
	SSourceLightData gsSourceLight_sys[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_sysmetric[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};
	
	SSourceLightData gsSourceLight_tan[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_transform[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_trim[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_upper[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_version[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_concatenate[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_add[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_sub[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_mul[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};

	SSourceLightData gsSourceLight_div[] =
	{
		{	0,										0,	0,	0,	0,	0	}
	};
