.PHONY: clean All

All:
	@echo "----------Building project:[ vjr64 - Debug ]----------"
	@$(MAKE) -f  "vjr64.mk"
clean:
	@echo "----------Cleaning project:[ vjr64 - Debug ]----------"
	@$(MAKE) -f  "vjr64.mk" clean
