.PHONY: clean All

All:
	@echo "----------Building project:[ vjr - Debug ]----------"
	@$(MAKE) -f  "vjr.mk"
clean:
	@echo "----------Cleaning project:[ vjr - Debug ]----------"
	@$(MAKE) -f  "vjr.mk" clean
